name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
            extra-conf: extra-experimental-features = nix-command flakes impure-derivations
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.BUILDER_TOKEN }}
      - uses: gacts/run-and-post-run@v1
        with:
          #run: nix flake check
          post: |
            mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
            ssh-keyscan cache.tcp4.me >> ~/.ssh/known_hosts
            TARGET="ssh://builder@cache.tcp4.me"
            nix copy --to $TARGET --all
