name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          install_url: https://releases.nixos.org/nix/nix-2.19.1/install
          extra_nix_config: |
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.BUILDER_TOKEN }}
      - uses: gacts/run-and-post-run@v1
        with:
          run: nix -v flake check -L --show-trace
          post: |
            TARGET="ssh://builder@cache.tcp4.me"
            mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
            cp .github/workflows/known_hosts ~/.ssh/known_hosts
            # took this filter list from cachix action
            find /nix/store -mindepth 1 -maxdepth 1 -type d -not -name ".*" -not -name "*.{drv,drv.chroot,check,lock}" | xargs -n 10 nix-copy-closure -k -s --to $TARGET
